### DNSMASQ-REGEX CONFIG
### BlackListed Domains ###
server=/a.medialaancdn.be/	# AdGuard
server=/affiliatepartners.com/	# AdGuard, EasyList
server=/mooieplaatjes.bierdopje.com/	# AdGuard, EasyList
server=/cambonus.com/	# AdGuard, EasyList
server=/ganaar.gertibaldi.com/	# AdGuard, EasyList
server=/gratis-neuken.com/	# AdGuard, EasyList
server=/ehg-advertisementbv.hitbox.com/	# AdGuard, EasyList
server=/hotlinkie.com/	# AdGuard, EasyList
server=/klikbonus.com/	# AdGuard, EasyList
server=/widget.pixspree.com/	# AdGuard, EasyList
server=/banners.toeto.com/	# AdGuard, EasyList
server=/asp.unitedconsumers.com/	# AdGuard, EasyList
server=/camsholland.eu/	# AdGuard, EasyList
server=/adconfigproxy.azurewebsites.net/	# AdGuard
server=/webvertising-img.bencom.net/	# AdGuard, EasyList
server=/c.dpgmedia.net/	# AdGuard, EasyList
server=/sp.dpgmedia.net/	# AdGuard, EasyList
server=/nonstoppartner.net/	# AdGuard, EasyList
server=/system.adquick.nl/	# AdGuard, EasyList
server=/tel.adversitement.nl/	# AdGuard, EasyList
server=/views.affiliate4you.nl/	# AdGuard, EasyList
server=/bnr.agf.nl/	# AdGuard, EasyList
server=/beekje.nl/	# AdGuard, EasyList
server=/bluemango.nl/	# AdGuard, EasyList
server=/camz.nl/	# AdGuard, EasyList
server=/cleafs.nl/	# AdGuard, EasyList
server=/csmcampagne.consumind.nl/	# AdGuard, EasyList
server=/conversive.nl/	# AdGuard, EasyList
server=/coolconcepts.nl/	# AdGuard, EasyList
server=/ds1.nl/	# AdGuard, EasyList
server=/europacams.nl/	# AdGuard, EasyList
server=/extremecash.nl/	# AdGuard, EasyList
server=/partnerwebsites.financereview.nl/	# AdGuard, EasyList
server=/schoorsteen.geenstijl.nl/	# AdGuard, EasyList
server=/gocams.nl/	# AdGuard, EasyList
server=/tools.islive.nl/	# AdGuard, EasyList
server=/kimhollandpartners.nl/	# AdGuard, EasyList
server=/banner.klikklik.nl/	# AdGuard, EasyList
server=/lauwebut.nl/	# AdGuard, EasyList
server=/lustcash.nl/	# AdGuard, EasyList
server=/views.m4n.nl/	# AdGuard, EasyList
server=/maakmedia.nl/	# AdGuard, EasyList
server=/mbs.midhold.nl/	# AdGuard, EasyList
server=/netdirect.nl/	# AdGuard, EasyList
server=/assets.nudeal.nl/	# AdGuard, EasyList
server=/pics.obedo.nl/	# AdGuard, EasyList
server=/online-banners.nl/	# AdGuard, EasyList
server=/partnerclicks.nl/	# AdGuard, EasyList
server=/content1.pcmweb.nl/	# AdGuard, EasyList
server=/pexi.nl/	# AdGuard, EasyList
server=/radiocoupon.nl/	# AdGuard, EasyList
server=/sallandacties.nl/	# AdGuard, EasyList
server=/am.seoptics.nl/	# AdGuard, EasyList
server=/marketing.teasemedia.nl/	# AdGuard, EasyList
server=/promotions.teasemedia.nl/	# AdGuard, EasyList
server=/topzorgverzekeringvergelijken.nl/	# AdGuard, EasyList
server=/banners.utilo.nl/	# AdGuard, EasyList
server=/verkoopmenu.nl/	# AdGuard, EasyList
server=/banners.vip.nl/	# AdGuard, EasyList
server=/vippromos.nl/	# AdGuard, EasyList
server=/vloerenvoordelig.nl/	# AdGuard, EasyList
server=/vpscash.nl/	# AdGuard, EasyList
server=/webflitser.nl/	# AdGuard, EasyList
server=/xpartners.nl/	# AdGuard, EasyList
server=/aj1716.online/	# AdGuard, EasyList
### EOF ###