### DNSMASQ CONFIG
### WhiteListed Domains ###
server=/concierge.analytics.console.aws.a2z.com/#	# NEXTDNS-EXCLUDE
server=/geo2.adobe.com/#	# NEXTDNS-EXCLUDE
server=/get3.adobe.com/#	# NEXTDNS-EXCLUDE
server=/ae01.alicdn.com/#	# NEXTDNS-EXCLUDE
server=/cloud.answerhub.com/#	# NEXTDNS-EXCLUDE
server=/raw.githubusercontent.com/#	# Source
server=/jnn-pa.googleapis.com/#	# NEXTDNS-EXCLUDE
server=/inc.com/#	# NEXTDNS-EXCLUDE
server=/browser.pipe.aria.microsoft.com/#	# NEXTDNS-EXCLUDE
server=/mobile.pipe.aria.microsoft.com/#	# NEXTDNS-EXCLUDE
server=/v10.events.data.microsoft.com/#	# NEXTDNS-EXCLUDE
server=/settings-win.data.microsoft.com/#	# NEXTDNS-EXCLUDE
server=/smartsheet.com/#	# NEXTDNS-EXCLUDE
server=/s.youtube.com/#	# NEXTDNS-EXCLUDE
server=/gov/#	# NEXTDNS-EXCLUDE
server=/teslarati-com-edge.ntv.io/#	# NEXTDNS-EXCLUDE
server=/app.link/#	# NEXTDNS-EXCLUDE
server=/whoami.akamai.net/#	# NEXTDNS-EXCLUDE
server=/lenta.ru/#	# NEXTDNS-EXCLUDE
### EOF ###