-- Whitelisted Domains
daf.add 'qname = concierge.analytics.console.aws.a2z.com pass'	 -- NEXTDNS-EXCLUDE
daf.add 'qname = geo2.adobe.com pass'	 -- NEXTDNS-EXCLUDE
daf.add 'qname = get3.adobe.com pass'	 -- NEXTDNS-EXCLUDE
daf.add 'qname = ae01.alicdn.com pass'	 -- NEXTDNS-EXCLUDE
daf.add 'qname = cloud.answerhub.com pass'	 -- NEXTDNS-EXCLUDE
daf.add 'qname = raw.githubusercontent.com pass'	 -- Source
daf.add 'qname = jnn-pa.googleapis.com pass'	 -- NEXTDNS-EXCLUDE
daf.add 'qname = inc.com pass'	 -- NEXTDNS-EXCLUDE
daf.add 'qname = browser.pipe.aria.microsoft.com pass'	 -- NEXTDNS-EXCLUDE
daf.add 'qname = mobile.pipe.aria.microsoft.com pass'	 -- NEXTDNS-EXCLUDE
daf.add 'qname = v10.events.data.microsoft.com pass'	 -- NEXTDNS-EXCLUDE
daf.add 'qname = settings-win.data.microsoft.com pass'	 -- NEXTDNS-EXCLUDE
daf.add 'qname = smartsheet.com pass'	 -- NEXTDNS-EXCLUDE
daf.add 'qname = s.youtube.com pass'	 -- NEXTDNS-EXCLUDE
daf.add 'qname = gov pass'	 -- NEXTDNS-EXCLUDE
daf.add 'qname = teslarati-com-edge.ntv.io pass'	 -- NEXTDNS-EXCLUDE
daf.add 'qname = app.link pass'	 -- NEXTDNS-EXCLUDE
daf.add 'qname = whoami.akamai.net pass'	 -- NEXTDNS-EXCLUDE
daf.add 'qname = lenta.ru pass'	 -- NEXTDNS-EXCLUDE
-- BlackListed Domains
-- EOF